project:
  type: website

website:
  title: "custom-callout"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/custom-callout/
  repo-actions: [edit, issue]
  sidebar:
    logo: "https://github.com/user-attachments/assets/7edadf64-a304-436c-b54f-2f76def14c14"
    logo-alt: "A hexagon logo for the custom-callout extension."
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/custom-callout/
    contents: 
      - text: "Home"
        file: index.qmd
      - text: "Example"
        file: qcustom-callout-example.qmd
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qcustom-callout-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/custom-callout/issues/new/choose
      - section: "Extra"
        contents:
        - qcustom-callout-release-notes.qmd
        - qcustom-callout-dev-notes.qmd

format: 
  html:
    toc: true