---
title: "Custom Callout Examples"
format:
  html:
    css: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css

custom-callout:    
  todo:
    icon-symbol: "📝"
    color: "pink"
  jjb:
    icon: true
    title: "fix for JJB"
    icon-symbol: "⚠️"
    color: "#FFA500"
  test:
    title: "Test feature"
    icon: true
    color: "#801410"
filters:
  - custom-callout
---

This document provides examples of custom callouts.

## Document YAML

The following YAML front matter is used to define custom callouts in this document:

````md
---
title: "Custom Callout Examples"
format: html
custom-callout:    
  todo:
    icon-symbol: "📝"
    color: "pink"
  jjb:
    icon: true
    title: "fix for JJB"
    icon-symbol: "⚠️"
    color: "#FFA500"
  test:
    title: "Test feature"
    icon: true
    color: "#801410"
filters:
  - custom-callout
---
````

## Sample Custom Callouts

The following examples demonstrate the use of custom callouts in Quarto documents using the defined styles in the YAML front matter.

### Original

:::{.panel-tabset}

### Rendered

::: todo
Hello there!
:::

::: jjb
Please address this issue ... 
:::

::: test
Let's do a feature test!
:::

### Source
````md
::: todo
Hello there!
:::

::: jjb
Please address this issue ... 
:::

::: test
Let's do a feature test!
:::
````
:::

### Title

:::{.panel-tabset}

### Rendered

::: {.todo title="Todo with a Custom Title!"}
Demo of `title="Todo with a Custom Title!"`.
:::

### Source

````md
::: {.todo title="Todo with a Custom Title!"}
Demo of `title="Todo with a Custom Title!"`.
:::
````
:::


### Icon

:::{.panel-tabset}

### Rendered

::: {.todo icon="false" title="Todo with No Icon"}
Demo of `icon="false"`.
:::

### Source

````md
::: {.todo icon="false" title="Todo with No Icon"}
Demo of `icon="false"`.
:::
````
:::

### Collapse


:::{.panel-tabset}

### Rendered
::: {.todo collapse="true" title="Collapsed Todo with Title"}
Demo of `collapse="true"`.
:::

### Source

````md
::: {.todo collapse="true" title="Collapsed Todo with Title"}
Demo of `collapse="true"`.
:::
````

:::

### Appearance

:::{.panel-tabset}

### Rendered
::: {.todo appearance="simple" title="Todo with Simple Appearance"}
Demo of `appearance="simple"`.
:::

::: {.todo appearance="minimal" title="Todo with Minimal Appearance"}
Demo of `appearance="minimal"`.
:::

### Source

````md
::: {.todo appearance="simple" title="Todo with Simple Appearance"}
Demo of `appearance="simple"`.
:::

::: {.todo appearance="minimal" title="Todo with Minimal Appearance"}
Demo of `appearance="minimal"`.
:::
````
:::

## Original Quarto Callout

This section provides examples of the built-in [Quarto Callout](https://quarto.org/docs/authoring/callouts.html) for a Note, e.g. `.callout-note`. 


:::{.panel-tabset}

### Rendered
::: {.callout-note}
Hello!
:::

::: {.callout-note collapse="true" title="Collapsed Note with Title"}
Demo of `collapse="true"`
:::

::: {.callout-note appearance="simple" title="Simple Note Appearance with Title"}
Demo of `appearance="simple"`.
:::

::: {.callout-note appearance="minimal" title="Minimal Note Appearance with Title"}
Demo of `appearance="minimal"`.
:::

### Source

````md
::: {.callout-note}
Hello!
:::

::: {.callout-note collapse="true" title="Collapsed Note with Title"}
Demo of `collapse="true"`
:::

::: {.callout-note appearance="simple" title="Simple Note Appearance with Title"}
Demo of `appearance="simple"`.
:::

::: {.callout-note appearance="minimal" title="Minimal Note Appearance with Title"}
Demo of `appearance="minimal"`.
:::
````
:::
